agent:
  api_key: "333"
  model: "doubao-seed-1-8-251228"
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
mysql:
  dsn: "root:123456@tcp(127.0.0.1:13306)/go_gin?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  addr: "localhost:6379"
  db: 0
  password: ""
app:
  port: 8888